### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [adambuchbinder/cordwainer-smith_short-fiction#1]
# General Issues:

- [x] Commits [`[Editorial] Fix spelling, 'Mattel'->'Martel'.`](https://github.com/adambuchbinder/cordwainer-smith_short-fiction/commit/010c2c2d77eeef567266eb04d8d3dd1108d42a1d) and [`[Editorial] 'And vet' -> 'And yet'. (Reported upstream.)`](https://github.com/adambuchbinder/cordwainer-smith_short-fiction/commit/31a562fce9fad7235e4dc456b12a952d2499c78c) should not be `[Editorial]`. Fixing transcription typos doesn't fall under [Editorial] commits. You will need to rename the commit messages with `git rebase -i`. Feel free to ask for help with the interactive rebase below this issue!  **Be sure to rebase commits before making any more commits.**

- [x] Commit [`[Editorial] Remove a few leftover Â bits.`](https://github.com/adambuchbinder/cordwainer-smith_short-fiction/commit/dc5c22a32e37dd0ff8746a0b8af9fea179223d00) should also not be `[Editorial]`. This is just correcting file structuring. You will need to edit the commit message.

- [x]  Commit [`[Editorial] Correct a number of nits:`](https://github.com/adambuchbinder/cordwainer-smith_short-fiction/commit/07d8c09997049e5fdddb91351344b849d4e3600a) has a mixture of editorial and non-editorial changes.

Non-editorial changes:
1. add period after Martel
2. add italics around `Danger`
3. comma --> period after `No`
4. add italics to `Scanners, an Illegality!`
5. remove italics from `thought Martel`

Editorial changes:
1. lowercase `Nail`
2. remove italics around `Chestbox`

This commit needs to be split. This can be done with `git rebase -i`. 

- [x] Add a `se-lint-ignore.xml` file to ignore the last lint error. See [SEMOS 2.4](https://standardebooks.org/manual/1.8.0/single-page#2.3) for more info.

- [x] **After fixing the issues below**, re-run `se build-toc .`

# scanners-live-in-vain.xhtml:

- [x] All `<i>` elements need to be changed to `<em>` elements.

- [x] The chapters' Arabic numerals need to be converted into Roman numerals ([SEMOS 8.1.1](https://standardebooks.org/manual/1.8.0/single-page#8.1.1)).

- [x] The chapter ids should be `id="scanners-live-in-vain-#"`. This specifies which chapters belong to which short story.

# the-game-of-rat-and-dragon.xhtml:

- [x] The chapter ids should be `id="the-game-of-rat-and-dragon-#"`. You can number the ids instead of using the titles for consistency.

# content.opf:

- [x] The short description should not contain proper names ([SEMOS 9.6.1.2](https://standardebooks.org/manual/1.8.0/single-page#9.6.1.2)).

- [x] If a production has multiple sources, use XML comments to specify the different parts of the ebook ([SEMOS 9.8.3.1](https://standardebooks.org/manual/1.8.0/single-page#9.8.3.1)).

**Comment by adambuchbinder** [comment]
All requested changes have been made, thank you.
